### ISSUE TITLE
(1.19.2) librget is not checking the villager's trade automatically 

### ISSUE THREAD

**Issue by TwoPointInfinity** [gXLg/libr-getter#5] opened 2022-11-20 02:19 UTC
im on a Spigot 1.19.2 server with no plugins (its a tad laggy) the only mods i have are fabric api and librget
https://youtu.be/CHROaU7gJMQ This is the issue im having. 
https://gyazo.com/cee9ccc1b71c9484635e83e4388d00ab

librget is not checking the villager for their trade automatically, i must right click them. 

The log does not show anything unusual. only that librget has started. 
https://gyazo.com/e0590d41793bc8246c433142b705cb8f

**Comment by TwoPointInfinity** [comment] 2022-11-20 02:45
it looks as if it's trying too soon, before it becomes a librarian. then not again when it fails.

**Comment by gXLg** [comment] 2022-11-20 05:50
Thanks, I will look into the issue

**Comment by TwoPointInfinity** [comment] 2022-11-20 06:21
as a current work around, keep the lecterns out of your offhand and use a right click auto clicker (program or in game mod) while looking at the villager.

**Comment by gXLg** [comment] 2022-11-20 11:32
I tried out the setup myself and can not cofirm this issue. Have you tried using LibrGetter after relogging on the server, and not selecting the villager again? This was the only way to reproduce the bug for me.

**Comment by TwoPointInfinity** [comment] 2022-11-20 22:37
i'll try a few things with reloging when i get to play later. it seems really inconsistent for me. sometimes it would check the enchant and sometime it would freeze up.

**Comment by gXLg** [comment] 2022-11-20 22:41
I will probably add an event to remove selcted entries on leaving a world, this way unexpected behaviour will be avoided. Please report back later on what you found out when you have time.

**Comment by TwoPointInfinity** [comment] 2022-11-21 06:41
https://youtu.be/oN5yXhDWJ-8

**Comment by TwoPointInfinity** [comment] 2022-11-21 06:42
when the villager shakes it head its because its being right clicked when it doesnt have a job. librget is trying to check the villager too early. Is it possible to make the mod wait until the selected villager becomes a librarian? 
I believe the issue is lag related, which would happen in a ton of situations and severs.

**Comment by TwoPointInfinity** [comment] 2022-11-21 06:46
or is it possible to add a check to see if an output was found after the enchantment check and if an output wasnt found yet, wait 5 ticks and try again?

**Comment by gXLg** [comment] 2022-11-21 07:08
> Is it possible to make the mod wait until the selected villager becomes a librarian? I believe the issue is lag related, which would happen in a ton of situations and severs.

This part is literally in the code, however when watching your video I saw, that the bug is related to something different.

The issue is, that after breaking the lectern and placing it again, villager did not manage to change profession because of lag and was clicked, because it was still a librarian. I will add an event after breaking the lectern to wait until villager loses its' profession.

Thank you for collaboration!

**Comment by gXLg** [comment] 2022-11-21 11:43
Fixed in [v1.2.5](https://github.com/gXLg/libr-getter/releases/tag/v1.2.5)

**Closed by gXLg** 2022-11-21 11:43 UTC
Labels: bug
